steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tos-repo/tos-streamlit:v6', '-f', 'app/Dockerfile', '.']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/tos-repo/tos-streamlit:v6'